// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjv6t1VOjcurReeVtjK6olEIOWu6uJIBk',
    appId: '1:924606652418:web:6c275d912a66ad65f7471b',
    messagingSenderId: '924606652418',
    projectId: 'sample1-5a63c',
    authDomain: 'sample1-5a63c.firebaseapp.com',
    storageBucket: 'sample1-5a63c.appspot.com',
    measurementId: 'G-CWMXVB58MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdmxrfbJSLTwvXoj-95EEVn83ZVAM0kLw',
    appId: '1:924606652418:android:e30040c667c85e07f7471b',
    messagingSenderId: '924606652418',
    projectId: 'sample1-5a63c',
    storageBucket: 'sample1-5a63c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeazVky8vq20k6WizjxN-v5tJS--dcXjU',
    appId: '1:924606652418:ios:c9038e2ce60a3f5ff7471b',
    messagingSenderId: '924606652418',
    projectId: 'sample1-5a63c',
    storageBucket: 'sample1-5a63c.appspot.com',
    iosClientId: '924606652418-r7mvpfjpe95g5uke2ktn5n2sfji1uir8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeazVky8vq20k6WizjxN-v5tJS--dcXjU',
    appId: '1:924606652418:ios:c9038e2ce60a3f5ff7471b',
    messagingSenderId: '924606652418',
    projectId: 'sample1-5a63c',
    storageBucket: 'sample1-5a63c.appspot.com',
    iosClientId: '924606652418-r7mvpfjpe95g5uke2ktn5n2sfji1uir8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample1',
  );
}
